export const CAPTION_LOOKS = [
  {
    id: 'viral-magenta',
    name: 'Viral Magenta',
    hint: 'White + hot pink keyword',
    sample: 'AT THE ENTIRE',
    sampleAccent: 'ENTIRE',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 32,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 5,
      outlineColor: '#000000',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 40,
      letterSpacing: -0.02,
      textTransform: 'uppercase',
      accentMode: 'last-word'
    },
    animation: { preset: 'none', highlightColor: '#FF2BD6', roundedBackground: false }
  },
  {
    id: 'viral-lemon',
    name: 'Viral Lemon',
    hint: 'White + yellow keyword',
    sample: 'WAIT FOR THIS',
    sampleAccent: 'THIS',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 32,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 5,
      outlineColor: '#000000',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 40,
      letterSpacing: -0.02,
      textTransform: 'uppercase',
      accentMode: 'last-word'
    },
    animation: { preset: 'none', highlightColor: '#FFE600', roundedBackground: false }
  },
  {
    id: 'viral-cyan',
    name: 'Viral Cyan',
    hint: 'White + electric blue',
    sample: 'WATCH THIS PART',
    sampleAccent: 'PART',
    style: {
      fontFamily: 'Impact',
      fontSize: 34,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 5,
      outlineColor: '#000000',
      shadowBlur: 6,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 38,
      letterSpacing: 0.01,
      textTransform: 'uppercase',
      accentMode: 'last-word'
    },
    animation: { preset: 'none', highlightColor: '#00E5FF', roundedBackground: false }
  },
  {
    id: 'viral-lime',
    name: 'Viral Lime',
    hint: 'White + green keyword',
    sample: 'DO THIS TODAY',
    sampleAccent: 'TODAY',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 32,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 5,
      outlineColor: '#000000',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 40,
      letterSpacing: -0.02,
      textTransform: 'uppercase',
      accentMode: 'last-word'
    },
    animation: { preset: 'none', highlightColor: '#B4FF2C', roundedBackground: false }
  },
  {
    id: 'viral-orange',
    name: 'Viral Orange',
    hint: 'White + orange keyword',
    sample: 'THE REAL REASON',
    sampleAccent: 'REASON',
    style: {
      fontFamily: 'Impact',
      fontSize: 34,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 5,
      outlineColor: '#111111',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 40,
      letterSpacing: 0,
      textTransform: 'uppercase',
      accentMode: 'last-word'
    },
    animation: { preset: 'none', highlightColor: '#FF7A00', roundedBackground: false }
  },
  {
    id: 'karaoke-pink',
    name: 'Karaoke Pink',
    hint: 'Spoken word fills magenta',
    sample: 'AT THE ENTIRE',
    sampleAccent: 'ENTIRE',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 30,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 4,
      outlineColor: '#000000',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 40,
      letterSpacing: -0.01,
      textTransform: 'uppercase',
      accentMode: 'spoken'
    },
    animation: { preset: 'karaoke', highlightColor: '#FF2BD6', roundedBackground: false }
  },
  {
    id: 'studio',
    name: 'Studio',
    hint: 'Clean product default',
    sample: 'Your story starts here',
    style: {
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: '700',
      textColor: '#F7F8FA',
      bgColor: '#0B0B0B',
      bgOpacity: 0.55,
      outlineWidth: 1,
      outlineColor: '#000000',
      shadowBlur: 6,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 36,
      letterSpacing: 0,
      textTransform: 'none'
    },
    animation: { preset: 'none', highlightColor: '#F59E0B', roundedBackground: true }
  },
  {
    id: 'netflix',
    name: 'Cinema',
    hint: 'No box, heavy stroke',
    sample: 'In a world of captions',
    style: {
      fontFamily: 'Noto Sans Devanagari',
      fontSize: 26,
      fontWeight: '700',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 3,
      outlineColor: '#000000',
      shadowBlur: 10,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 42,
      letterSpacing: 0.01,
      textTransform: 'none'
    },
    animation: { preset: 'fade-in', highlightColor: '#FFFFFF', roundedBackground: false }
  },
  {
    id: 'hormozi',
    name: 'Punch',
    hint: 'Word highlight, uppercase',
    sample: 'STOP scrolling now',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 28,
      fontWeight: '900',
      textColor: '#FFFFFF',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 3,
      outlineColor: '#111111',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'center',
      marginV: 24,
      letterSpacing: 0.04,
      textTransform: 'uppercase'
    },
    animation: { preset: 'highlight-word', highlightColor: '#F5D90A', roundedBackground: true }
  },
  {
    id: 'karaoke',
    name: 'Karaoke',
    hint: 'Fill the active word',
    sample: 'Sing every word',
    style: {
      fontFamily: 'Poppins',
      fontSize: 26,
      fontWeight: '800',
      textColor: '#F8FAFC',
      bgColor: '#000000',
      bgOpacity: 0.35,
      outlineWidth: 2,
      outlineColor: '#0F172A',
      shadowBlur: 6,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 34,
      letterSpacing: 0.01,
      textTransform: 'none'
    },
    animation: { preset: 'karaoke', highlightColor: '#22D3EE', roundedBackground: false }
  },
  {
    id: 'gold',
    name: 'Gold Reels',
    hint: 'Amber pill, tight tracking',
    sample: 'यो लुक तयार छ',
    style: {
      fontFamily: 'Noto Sans Devanagari',
      fontSize: 25,
      fontWeight: '800',
      textColor: '#FFF7E6',
      bgColor: '#1A1206',
      bgOpacity: 0.72,
      outlineWidth: 1,
      outlineColor: '#7C4A03',
      shadowBlur: 8,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 38,
      letterSpacing: 0.02,
      textTransform: 'none'
    },
    animation: { preset: 'bounce', highlightColor: '#F59E0B', roundedBackground: true }
  },
  {
    id: 'serif',
    name: 'Editorial',
    hint: 'Cinematic serif',
    sample: 'Quiet, then the cut',
    style: {
      fontFamily: 'Playfair Display',
      fontSize: 28,
      fontWeight: '700',
      textColor: '#FFF8EE',
      bgColor: '#000000',
      bgOpacity: 0.28,
      outlineWidth: 1,
      outlineColor: '#2A2118',
      shadowBlur: 12,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 48,
      letterSpacing: 0.03,
      textTransform: 'none'
    },
    animation: { preset: 'slide-up', highlightColor: '#E8C39E', roundedBackground: false }
  },
  {
    id: 'teko',
    name: 'Sport',
    hint: 'Condensed display',
    sample: 'GAME ON',
    style: {
      fontFamily: 'Teko',
      fontSize: 36,
      fontWeight: '700',
      textColor: '#FAFAFA',
      bgColor: '#DC2626',
      bgOpacity: 0.9,
      outlineWidth: 0,
      outlineColor: '#000000',
      shadowBlur: 0,
      shadowColor: '#000000',
      position: 'bottom',
      marginV: 28,
      letterSpacing: 0.08,
      textTransform: 'uppercase'
    },
    animation: { preset: 'pulse', highlightColor: '#FFFFFF', roundedBackground: true }
  },
  {
    id: 'ghost',
    name: 'Ghost',
    hint: 'Bare type, soft shadow',
    sample: 'almost invisible',
    style: {
      fontFamily: 'Inter',
      fontSize: 22,
      fontWeight: '500',
      textColor: '#F4F4F5',
      bgColor: '#000000',
      bgOpacity: 0,
      outlineWidth: 0,
      outlineColor: '#000000',
      shadowBlur: 14,
      shadowColor: 'rgba(0,0,0,0.85)',
      position: 'bottom',
      marginV: 40,
      letterSpacing: 0.06,
      textTransform: 'lowercase'
    },
    animation: { preset: 'fade-in', highlightColor: '#A1A1AA', roundedBackground: false }
  }
];
